name: Terraform Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight, adjust as needed

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform-cleanup:
    name: "Post Apply Cleanup"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub repository"
        uses: actions/checkout@v2

      - name: Authenticate to AWS Cloud
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE }}
          role-session-name: terraform-role-session
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan Destroy"
        run: terraform plan -destroy -out=tfplan-destroy

      - name: "Terraform Apply Destroy"
        run: terraform apply -auto-approve tfplan-destroy
